media:
  input: "assets"
  output: "/"

content:
  - name: "hero_data"
    label: HeroData
    type: file
    path: "_data/hero.json"
    list: false
    fields:
      - name: greeting
        type: string
      - name: summury
        type: text
      - name: image
        type: image
      - name: resume
        type: file
  - name: "certificates"
    label: "Certificates"
    type: file
    path: "_data/certificates.json"
    list: true
    fields:
      - name: title
        type: string
      - name: issuer
        type: string
      - name: date
        type: date
      - name: image
        type: image
      - name: url
        type: string

  - name: projects
    label: Projects
    type: file
    path: "_data/projects.json"
    list: true
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: longDescription
        type: text
      - name: techStack
        type: string
        options:
          multiple: true
      - name: images
        type: image
        options:
          multiple: true
          unique: true
          extensions: [jpg, png, webp]
          rename: true
      - name: githubUrl
        label: GitHub URL
        type: string
      - name: liveUrl
        label: Live URL
        type: string
      - name: date
        type: date
      - name: status
        type: select
        options:
          values:
            - completed
            - in progress
            - archived
    
  - name: events
    label: Events
    type: file
    path: "_data/events.json"
    list: true
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: myRole
        type: string
      - name: expandedRole
        type: text
      - name: takeaways
        type: text
      - name: location
        type: string
      - name: images
        type: image
        options:
          multiple: true
          unique: true
          extensions: [jpg, png, webp]
          rename: true
      - name: date
        type: date